### ISSUE TITLE
False sense of security

### ISSUE THREAD

**Issue by jaghaimo** [Lukas22041/LunaLib#2]
![image](https://github.com/Lukas22041/LunaLib/assets/1764586/f7016a07-c9c5-4c7c-83ad-c5d4114af47d)

The last sentence gives a false sense of security – if you don't open those links, you're fine. Malware may very much be compressed and distributed as zip or rar files. Suggest changing it with a generic warning to be careful and vigilant when downloading any file from the internet.

**Comment by Lukas22041** [comment]
That is indeed true, i changed the phrasing in the next dev build to be more general.
